/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"

#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_status2d.c"
#include "bar_statuscmd.c"
#include "bar_tags.c"
#include "bar_wintitle.c"
#include "bar_flexwintitle.c"
#include "bar_systray.c"
#include "bar_wintitleactions.c"
#include "bar_layoutmenu.c"

/* Other patches */
#include "autostart.c"
#include "cfacts.c"
#include "cool_autostart.c"
#include "cyclelayouts.c"
#include "dragcfact.c"
#include "fullscreen.c"
#include "killunsel.c"
#include "pertag.c"
#include "placemouse.c"
#include "restartsig.c"
#include "scratchpad.c"
#include "scratchpad_alt_1.c"
#include "selfrestart.c"
#include "shiftview.c"
#include "togglefullscreen.c"
#include "vanitygaps.c"
#include "dragmfact.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_bstack.c"
#include "layout_centeredmaster.c"
#include "layout_centeredfloatingmaster.c"
#include "layout_deck.c"
#include "layout_fibonacci.c"
#include "layout_flextile-deluxe.c"
#include "layout_monocle.c"
#include "layout_tile.c"

