/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"

#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_status2d.h"
#include "bar_statuscmd.h"
#include "bar_tags.h"
#include "bar_wintitle.h"
#include "bar_flexwintitle.h"
#include "bar_systray.h"
#include "bar_wintitleactions.h"
#include "bar_layoutmenu.h"

/* Other patches */
#include "autostart.h"
#include "cfacts.h"
#include "cool_autostart.h"
#include "cyclelayouts.h"
#include "dragcfact.h"
#include "dragmfact.h"
#include "fullscreen.h"
#include "killunsel.h"
#include "pertag.h"
#include "placemouse.h"
#include "restartsig.h"
#include "scratchpad.h"
#include "scratchpad_alt_1.h"
#include "selfrestart.h"
#include "shiftview.h"
#include "togglefullscreen.h"
#include "vanitygaps.h"
/* Layouts */
#include "layout_bstack.h"
#include "layout_centeredmaster.h"
#include "layout_centeredfloatingmaster.h"
#include "layout_deck.h"
#include "layout_fibonacci.h"
#include "layout_flextile-deluxe.h"
#include "layout_monocle.h"
#include "layout_tile.h"

